// Every documented spelling of a shape, mapped to the registry key it is
// filed under (see registry.ts).
//
// This is Mermaid's own alias table, lifted verbatim from the shape registry
// in mermaid@12, so `@{ shape: database }` and `@{ shape: cyl }` land
// together. Two readers share it: the Mermaid importer (mermaid/toOrdo.ts),
// and the Ordo reader, which accepts these names as well as the registry's
// own keys, so a hand-written file can say `shape: cylinder` (see
// ordo/rf-mapping.ts). Nothing writes an alias back out: the canvas only ever
// holds registry keys.
export const SHAPE_ALIASES: Record<string, string> = {
  "bow-tie-rectangle": "bow-rect",
  "brace-l": "brace",
  card: "notch-rect",
  circ: "circle",
  collate: "hourglass",
  "com-link": "bolt",
  comment: "brace",
  "crossed-circle": "cross-circ",
  "curved-trapezoid": "curv-trap",
  cylinder: "cyl",
  das: "h-cyl",
  "data-store": "datastore",
  database: "cyl",
  db: "cyl",
  decision: "diam",
  diamond: "diam",
  directory: "folder",
  disk: "lin-cyl",
  display: "curv-trap",
  "div-proc": "div-rect",
  "divided-process": "div-rect",
  "divided-rectangle": "div-rect",
  document: "doc",
  documents: "docs",
  "double-circle": "dbl-circ",
  event: "rounded",
  extract: "tri",
  "filled-circle": "f-circ",
  "flipped-triangle": "flip-tri",
  "framed-circle": "fr-circ",
  "framed-rectangle": "fr-rect",
  "half-rounded-rectangle": "delay",
  hexagon: "hex",
  "horizontal-cylinder": "h-cyl",
  "in-out": "lean-r",
  "internal-storage": "win-pane",
  "inv-trapezoid": "trap-t",
  join: "fork",
  junction: "f-circ",
  "lean-left": "lean-l",
  "lean-right": "lean-r",
  "lightning-bolt": "bolt",
  "lin-proc": "lin-rect",
  "lined-cylinder": "lin-cyl",
  "lined-document": "lin-doc",
  "lined-process": "lin-rect",
  "lined-rectangle": "lin-rect",
  "loop-limit": "notch-pent",
  manual: "trap-t",
  "manual-file": "flip-tri",
  "manual-input": "sl-rect",
  "notched-pentagon": "notch-pent",
  "notched-rectangle": "notch-rect",
  "out-in": "lean-l",
  "paper-tape": "flag",
  pill: "stadium",
  prepare: "hex",
  priority: "trap-b",
  proc: "rect",
  process: "rect",
  processes: "st-rect",
  procs: "st-rect",
  question: "diam",
  rectangle: "rect",
  "shaded-process": "lin-rect",
  "sloped-rectangle": "sl-rect",
  "small-circle": "sm-circ",
  "st-doc": "docs",
  "stacked-document": "docs",
  "stacked-rectangle": "st-rect",
  start: "sm-circ",
  stop: "fr-circ",
  "stored-data": "bow-rect",
  subproc: "fr-rect",
  subprocess: "fr-rect",
  subroutine: "fr-rect",
  summary: "cross-circ",
  "tag-proc": "tag-rect",
  "tagged-document": "tag-doc",
  "tagged-process": "tag-rect",
  "tagged-rectangle": "tag-rect",
  terminal: "stadium",
  trapezoid: "trap-b",
  "trapezoid-bottom": "trap-b",
  "trapezoid-top": "trap-t",
  triangle: "tri",
  "window-pane": "win-pane",
};
